# .swiftlint.yml

# Paths to include (default is all Swift files)

# Opt-in rules (rules that are disabled by default)
opt_in_rules:
  - explicit_init
  - missing_docs

# Customizable rules
line_length:
  warning: 120
  error: 150
  ignores_comments: true
  ignores_function_declarations: true

# Specific rules
force_cast:
  severity: error
  
# Reporter options
reporter: "xcode" # alternative: json, csv, checkstyle
